    IF !DEF(CONSTANTS_INCLUDED)
CONSTANTS_INCLUDED SET 1

;;;;;;;;;;;;;; HEADER OPTIONS ;;;;;;;;;;;;;;;;;
NO_COLOUR_SUPPORT EQU $00
COLOUR_SUPPORT EQU $80
COLOUR_ONLY EQU $C0

UNLICENSED EQU "00"

SGB_SUPPORTED EQU $03
ROM_ONLY EQU $00
ROM_MBC1 EQU $01
ROM_MBC1_RAM EQU $02

ROM_32KB EQU $00
RAM_8KB EQU $02

FOREIGN_DESTINATION EQU $01

USE_NEW_LICENSEE_CODE EQU $33

;;;;;;;;;;;;;; DMA Related ;;;;;;;;;;;;;;;;;;

DMA_WAIT_TIME EQU $28
ENDC