JoypadLabel:    dbs "Test Joypad" 
SGBLabel:       dbs "Test Super GB"
AudioLabel:     dbs "Test Audio"
JoypadTestInstructions: dbs "Rst:A+B+Start+Select"
SgbStepTitle:   dbs "Select Command Type"
MltReqLabel:    dbs "MLT_REQ"
PalPqLabel:     dbs "PALxx"
AttrLinLabel:   dbs "ATTR_LIN"
MaskEnLabel:    dbs "MASK_EN"
MaskFrozen:     dbs "FRZ"
MaskBlack:      dbs "BLK"
MaskColour:     dbs "CLR"
