JoypadLabel:    dbs "Test Joypad" 
SGBLabel:       dbs "Test Super GB"
AudioLabel:     dbs "Test Audio"
JoypadTestInstructions: dbs "Rst:A+B+Start+Select"
SgbStepTitle:   dbs "Select Command Type"
InitialiseSGB:  dbs "Initialisation"
MltReqLabel:    dbs "MLT_REQ"
PalPqLabel:     dbs "PALxx"
AttrLinLabel:   dbs "ATTR_LIN"
MaskEnLabel:    dbs "MASK_EN"
PctTrnLabel:    dbs "PCT_TRN"
MaskFrozen:     dbs "FRZ"
MaskBlack:      dbs "BLK"
MaskColour:     dbs "CLR"
Pal01:          dbs "01"
Pal23:          dbs "23"
Pal03:          dbs "03"
Pal12:          dbs "12"
SendCommand:    dbs "Send"
